# Generated by Django 3.1.7 on 2021-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_mode', models.CharField(choices=[('clean', 'clean'), ('shape', 'shape'), ('color', 'color'), ('face', 'face')], default='clean', max_length=6)),
            ],
        ),
    ]
