# Generated by Django 3.1.7 on 2021-04-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210413_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circledetectionmodel',
            name='maxRadius',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='circledetectionmodel',
            name='minDist',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='circledetectionmodel',
            name='minRadius',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='circledetectionmodel',
            name='param1',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='circledetectionmodel',
            name='param2',
            field=models.FloatField(default=70),
        ),
    ]
