# Generated by Django 3.1.7 on 2021-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210413_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriangleDetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernelShape', models.IntegerField(default=4)),
                ('approximation', models.FloatField(default=0.02)),
                ('maxArea', models.FloatField(default=400)),
            ],
        ),
    ]
