# Generated by Django 3.1.7 on 2021-04-28 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_colorhsvdetectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_hue',
            field=models.IntegerField(default=160, validators=[django.core.validators.MaxValueValidator(359), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_hue',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(359), django.core.validators.MinValueValidator(0)]),
        ),
    ]
