# Generated by Django 3.1.7 on 2021-04-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210428_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_hue',
            field=models.IntegerField(default=80),
        ),
    ]
