# Generated by Django 3.1.7 on 2021-04-28 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210428_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_hue',
            field=models.PositiveIntegerField(default=160, validators=[django.core.validators.MaxValueValidator(359), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_saturation',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_value',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_hue',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(359), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_saturation',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_value',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='triangleandsquaredetectionmodel',
            name='kernelShape',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
