# Generated by Django 3.1.7 on 2021-04-29 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210428_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRGBDetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('green_min', models.PositiveIntegerField(default=51, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('blue_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('red_max', models.PositiveIntegerField(default=102, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('green_max', models.PositiveIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('blue_max', models.PositiveIntegerField(default=102, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
