# Generated by Django 3.1.7 on 2021-04-29 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_colorrgbdetectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorrgbdetectionmodel',
            name='blue_max',
            field=models.PositiveIntegerField(default=171, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorrgbdetectionmodel',
            name='blue_min',
            field=models.PositiveIntegerField(default=41, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorrgbdetectionmodel',
            name='red_max',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorrgbdetectionmodel',
            name='red_min',
            field=models.PositiveIntegerField(default=48, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
    ]
