# Generated by Django 3.1.7 on 2021-05-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210429_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circledetectionmodel',
            old_name='maxRadius',
            new_name='max_radius',
        ),
        migrations.RenameField(
            model_name='circledetectionmodel',
            old_name='minDist',
            new_name='min_dist',
        ),
        migrations.RenameField(
            model_name='circledetectionmodel',
            old_name='minRadius',
            new_name='min_radius',
        ),
        migrations.RenameField(
            model_name='triangleandsquaredetectionmodel',
            old_name='kernelShape',
            new_name='kernel_shape',
        ),
        migrations.RenameField(
            model_name='triangleandsquaredetectionmodel',
            old_name='maxArea',
            new_name='max_area',
        ),
    ]
