# Generated by Django 3.1.7 on 2021-05-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210502_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_scale_factor', models.FloatField(default=1.05)),
                ('face_min_neighbors', models.PositiveIntegerField(default=6)),
                ('face_min_size', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('face_max_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EyesDetectionModel',
            fields=[
                ('facedetectionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.facedetectionmodel')),
                ('eye_scale_factor', models.FloatField(default=1.3)),
                ('eye_min_neighbors', models.PositiveIntegerField(default=5)),
                ('eye_min_size', models.PositiveIntegerField(blank=True, null=True)),
                ('eye_max_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('main.facedetectionmodel',),
        ),
    ]
