# Generated by Django 3.1.7 on 2021-05-06 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_eyesdetectionmodel_facedetectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_saturation',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='max_value',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_saturation',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='colorhsvdetectionmodel',
            name='min_value',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
